Add Australian ICSM transformation grids
OSGeo/proj-datumgrid pull request #3
Opened 2018-02-07 23:59 UTC by nyalldawson

(Alternative version of https://github.com/OSGeo/proj.4/pull/708)

These files are available under a CC-BY-4.0 license from https://github.com/icsm-au/transformation_grids

2018-02-13 03:44 UTC, andrewharvey commented
https://github.com/OSGeo/proj-datumgrid/pull/3/files#diff-423261653a17fd954e957602ebb5ce13L1 shoud be updated to include Australia or just removed to avoid a long list of counties in the title?

2018-02-13 03:55 UTC, nyalldawson commented
I'd suggest removing it - it'll only get longer in future...

2018-02-14 12:39 UTC, kbevers requested changes
I have a few change request in in-line comments. Fix those and we can include the Australian grids in version 1.7 of the datumgrid package which will have to be released together with PROJ 5.0.0.

2018-02-14 12:39 UTC, kbevers commented on A66_National_13_09_01.LICENSE.md
> +Licensed under a Creative Commons Attribution 4.0 Licence.
I don't think these license files are needed. A reference to the publishing authoritys website should be enough. As far as I can tell it is this one https://github.com/icsm-au/transformation_grids and a clear statement in `GRIDS.md` which license is attached to each grid.

2018-02-14 12:39 UTC, kbevers commented on README.DATUMGRID
> +Australia	(sourced from https://github.com/icsm-au/transformation_grids)
Please move this info to the `GRIDS.md` file instead.

2018-02-15 03:07 UTC, nyalldawson commented
@kbevers PR updated

2018-02-15 12:41 UTC, kbevers approved these changes

2018-02-15 12:41 UTC, merged